name: Check Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"
      - name: Install build dependencies
        run: python -m pip install --upgrade pip wheel twine build
      - name: Build package
        run: python -m build
      - name: Check package
        run: twine check --strict dist/*.whl
